### ISSUE TITLE
Error on creating alpine image

### ISSUE THREAD

**Issue by araeubig** [Automattic/vip-codespaces#48]
While trying to use the codespace base i got an error on creating the alpine image - until yesterday it works perfect but after your last merge it doesnt work with the following error:

![image](https://user-images.githubusercontent.com/129953354/234481102-068fc818-75b4-46af-a984-528fe10b704f.png)

I only changed all image references from /automattic/ to /my-user/

**Comment by sjinks** [comment]
It could be because of `@devcontainers/cli` 0.40.

I built everything with 0.39.

You may want to try to change

```diff
-        run: npm install -g @devcontainers/cli
+        run: npm install -g @devcontainers/cli@0.39.0
```

in `.github/.workflows/*.yml`

**Comment by sjinks** [comment]
Actually I see a problem on line 17 - something is wrong with image tag.

**Comment by sjinks** [comment]
See https://github.com/araeubig/vip-codespaces/pull/2 for the fix.
