### ISSUE TITLE
Feature "wordpress"

### ISSUE THREAD

**Issue by araeubig** [Automattic/vip-codespaces#53]
Install of wordpress feature works but installs always with standard language "en_EN" - Trying to change the part by adding locale attribute doesn't - the installation is always english:

 wp core install \
            --path=/wp \
            --url="${wp_url}" \
            --title="${wp_title}" \
            --admin_user="admin" \
            --admin_email="admin@localhost.local" \
            --admin_password="password" \
            --locale=de_DE  \
            --skip-email \
            --skip-plugins \
            --skip-themes

I don't know if it depends on the WP-CLI version but want to inform you about this.

Regards André

**Comment by sjinks** [comment]
We download WordPress without `wp-content`; this could be the reason.

If you run

```
wp language core install de_DE --activate
```

does it work?

**Comment by araeubig** [comment]
I only added the locale attribute into your defined set of arguments in features/wordpress-set. Removing the other attributes would end with a installation without user and password and no possibility to test?

**Comment by araeubig** [comment]
> We download WordPress without `wp-content`; this could be the reason.
> 
> If you run
> 
> ```
> wp language core install de_DE --activate
> ```
> 
> does it work?

Sorry but i read to quick - to install the language after the core download works - but the "first" added options are in english. For me not a problem but i tried to think further. I have setup a new local repo based on your work and try some changes with the core install. You will certainly get a feedback.

**Comment by araeubig** [comment]
And finally i added the --locale to the main download in install.sh and it works perfect.

**Comment by sjinks** [comment]
In WPVIP, we [handle such things differently](https://docs.wpvip.com/technical-references/vip-codebase/).

Basically, we have a bare WordPress on a read-only file system and [user code from vip-go-skeleton](https://github.com/Automattic/vip-go-skeleton) mounted into proper locations. Languages, themes, and plugins are controlled by the user; this is why we have `--skip-content` in `wp core download` and do not configure locales etc.
