### ISSUE TITLE
MySQL error after rebuilding codespace

### ISSUE THREAD

**Issue by araeubig** [Automattic/vip-codespaces#55]
In my test devcontainer (based completely on your main alpine image and all of your feature sets) i tried to stop the codespace and re-run it -> wordpress opens with startmask of installation and asking for installation language and by opening phpmyadmin i get an mysqli error.

First build:

![Screenshot (63)](https://user-images.githubusercontent.com/129953354/235414647-19e3e0aa-73ed-432f-91fc-12e2700b1bd5.png)

Rebuild:

![Screenshot (64)](https://user-images.githubusercontent.com/129953354/235414680-9ad55a74-7764-4aba-bcca-29a96281a22a.png)

I don't know if it depends on my manual try to start your configuration but i copied it 1:1 from your actual base. Perhaps it is an open issue which you haven't seen until now.

I think WordPress and MariaDB do not read the config file correct - the database folder is present in the workspace and the WordPress table is present.

Regards André

**Comment by sjinks** [comment]
Yes, I tried to fix it in #52 with no luck. It works with a different configuration, though.

The only affected database is `mysql`. That is, if you rerun the `setup-wordpress.sh`, it will readd the `wordpress` user into `mysql` database and everything will work.

**Comment by araeubig** [comment]
Perhaps you will find a working solution for rebuilding database connection with this container-creation?

Actually i have made a hard copy and try to test some extensions, additions and let you know if some of them are successful.
The installation in another language works fine but now i will try to use your way of installation and configuration to make it extendable.

I tried yesterday to integrate loco-translate as an mu-plugin but this seems to work not really. The screen layout was completely "reduced" based on a lot of missing or wrong CSS shortcuts.

Regards André

**Comment by sjinks** [comment]
Fixed in f08cede
